### PR TITLE
New file about jupiter!

### PR DESCRIPTION
**Pull request by bpteague**
Add this thing about Jupiter please...

### CODE REVIEW

**Comment by bpteague** [comment]
I think we should talk about Jupiter's moons.

**Comment by bpteague** [comment]
I think @danabauer might have something to say about this.

**Comment by danabauer** [comment]
Yes! I prefer Saturn with its lovely rings.

**Comment by exowanderer** [comment]
Are we considering Earth as a planet for this project?

**Comment by wienbob** [comment]
Jupiter has at least 67 "known" moons.  Saturn only has 62 known moons, 9 of which haven't been named yet.  Uranus has 27 known moons, Neptune has 14 known moons, and Pluto (not considered a planet at this time) has 5.  Mercury and Venus do not have any moons, Earth has 1, Mars has 2.  There are no moons because it would have an unstable orbit and likely sucked into the Sun.

**Pull request merged**
